version: '2'

services:
  db:
    container_name: db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  app:
    container_name: app
    build: ./app
    restart: always
    command: npm start
    volumes:
      - ./app/src:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      #Database URL
      - DB_URL=mongodb://db:27017/adc?connectTimeoutMS=1000