version: '2'

services:
  db:
    image: aashreys/mongo-auth
    ports: 
      - 27017:27017
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin123
      - MONGODB_APPLICATION_DATABASE=databaseName
      - MONGODB_APPLICATION_USER=john
      - MONGODB_APPLICATION_PASS=doe
    volumes:
      - ./data:/data/db

  app:
    build: ./app
    tty: true
    restart: always
    command: npm start
    volumes:
      - ./app/src:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
